#Coleta de dados manual para que fosse feita o data-frame com as premiações e informações dos albuns
ordem_albunsdf = ["Transpiração Contínua Prolongada",
"Preço Curto... Prazo Longo",
"Nadando com os Tubarões",
"100% Charlie Brown Jr. - Abalando a Sua Fábrica",
"Bocas Ordinárias",
"Acústico MTV: Charlie Brown Jr.",
"Tamo Aí na Atividade",
"Imunidade Musical",
"Ritmo, Ritual e Responsa",
"Música Popular Caiçara ao Vivo",
"Camisa 10 Joga Bola Até na Chuva",
"La Familia 013 ",
]

premios_albumdf = ["-",
"-",
"-",
"-",
"-",
"-",
"Grammy Latino",
"-",
"-",
"-",
"Grammy Latino",
"Prêmio Rock Show",
]

categorias_premio = ["-",
"-",
"-",
"-",
"-",
"-",
"Melhor Álbum de Rock Brasileiro",
"-",
"-",
"-",
"Melhor Álbum de Rock Brasileiro",
"Disco do Ano",
]

certificacoes_albuns =["PMB: Platina",
"PMB: Platina",
"PMB: Ouro",
"-",
"PMB: Ouro",
"PMB: Platina",
"PMB: Platina",
"PMB: Ouro",
"-",
"-",
"PMB: Platina",
"-",
]

data_lanc_albuns = ["16 de junho de 1997",
" 9 de abril de 1999",
"Novembro de 2000",
"30 de abril de 2001",
"12 de maio de 2002",
"20 de setembro de 2003",
"Novembro de 2004",
"23 de agosto de 2005",
"15 de novembro de 2007",
"Maio de 2012",
"25 de setembro de 2009",
"8 de outubro de 2013",
]
